controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    flipper_controller1:
      type: position_controllers/JointGroupPositionController

    flipper_controller2:
      type: position_controllers/JointGroupPositionController
    
    flipper_controller3:
      type: position_controllers/JointGroupPositionController
    
    flipper_controller4:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

flipper_controller1:
  ros__parameters:
    joints:
      - left_flipper_joint

flipper_controller2:
  ros__parameters:
    joints:
      - right_flipper_joint


flipper_controller3:
  ros__parameters:
    joints:
      - rear_left_flipper_joint

flipper_controller4:
  ros__parameters:
    joints:
      - rear_right_flipper_joint

